# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  rspec:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: myapp
          RAILS_ENV: test
      - image: postgres:9.6
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1.4-dependencies-rspec-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1.4-dependencies-rspec-

      - run:
          name: install dependencies
          command:  bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1.4-dependencies-rspec-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: create Database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      # run tests!
      # Change to rspec if you are using rspec
      - run:
          name: run rspec
          command: |
            bundle exec rspec --tag ~rubocop \
            --format progress --format RspecJunitFormatter -o tmp/test-results/rspec.xml

      # collect reports
      - store_test_results:
          path: tmp/test-results/
      - store_artifacts:
          path: tmp/test-results/
          destination: test-results

  rubocop:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: myapp
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1.4-dependencies-rubocop-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1.4-dependencies-rubocop-

      - run:
          name: install dependencies
          command:  bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1.4-dependencies-rubocop-{{ checksum "Gemfile.lock" }}

      # run rubocop!
      - run:
          name: run rubocop
          command: |
            bundle exec rspec spec/lint/ \
            --format progress --format RspecJunitFormatter -o tmp/test-results/rubocop.xml

      # collect reports
      - store_test_results:
          path: tmp/test-results/
      - store_artifacts:
          path: tmp/test-results/
          destination: test-results

workflows:
  version: 2
  rspec_and_rubocop:
    jobs:
      - rspec
      - rubocop
