# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  rspec:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: myapp
          RAILS_ENV: test
      - image: postgres:9.6
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo/taskmanager_app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1.2-dependencies-{{ checksum "taskmanager_app/Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1.2-dependencies-

      - run:
          name: install dependencies
          command:  bundle install --jobs=4 --retry=3 --path vendor/bundle
          working_directory: taskmanager_app
      - save_cache:
          paths:
            - taskmanager_app/vendor/bundle
          key: v1.2-dependencies-{{ checksum "taskmanager_app/Gemfile.lock" }}

      # Database setup
      - run:
          name: create Database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
          working_directory: taskmanager_app

      # run tests!
      # Change to rspec if you are using rspec
      - run:
          name: run rspec
          command: |
            bundle exec rspec --tag ~rubocop \
            --format progress --format RspecJunitFormatter -o tmp/test-results/rspec.xml
          working_directory: taskmanager_app

      # collect reports
      - store_test_results:
          path: taskmanager_app/tmp/test-results/
      - store_artifacts:
          path: taskmanager_app/tmp/test-results/
          destination: test-results

  rubocop:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: myapp
          RAILS_ENV: test

    working_directory: ~/repo/taskmanager_app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1.2-dependencies-{{ checksum "taskmanager_app/Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1.2-dependencies-

      - run:
          name: install dependencies
          command:  bundle install --jobs=4 --retry=3 --path vendor/bundle
          working_directory: taskmanager_app
      - save_cache:
          paths:
            - taskmanager_app/vendor/bundle
          key: v1.2-dependencies-{{ checksum "taskmanager_app/Gemfile.lock" }}

      # run rubocop!
      - run:
          name: run rubocop
          command: |
            bundle exec rspec spec/lint/ \
            --format progress --format RspecJunitFormatter -o tmp/test-results/rubocop.xml
          working_directory: taskmanager_app

      # collect reports
      - store_test_results:
          path: taskmanager_app/tmp/test-results/
      - store_artifacts:
          path: taskmanager_app/tmp/test-results/
          destination: test-results

workflows:
  version: 2
  rspec_and_rubocop:
    jobs:
      - rspec
      - rubocop
